CREATE TABLE Registro  (
    RBD INT NOT NULL,
    Date INT NOT NULL,

    APR_SI_TO INT NULL,
    APR_HOM_TO INT NOT NULL,
    APR_MUJ_TO INT NOT NULL,
    REP_HOM_TO INT NOT NULL,
    REP_MUJ_TO INT NOT NULL,
    SI_HOM_TO INT NULL,
    SI_MUJ_TO FLOAT NULL,
    TRA_HOM_TO INT NOT NULL,
    TRA_MUJ_TO INT NOT NULL,
    RET_HOM_TO INT NOT NULL,
    RET_MUJ_TO FLOAT NULL,
    PROM_ASIS_APR_HOM FLOAT NULL,
    PROM_ASIS_APR_MUJ FLOAT NULL,
    PROM_ASIS_APR_SI FLOAT NULL,
    PROM_ASIS_APR FLOAT NULL,
    PROM_ASIS_REP_HOM FLOAT NULL,
    PROM_ASIS_REP_MUJ FLOAT NULL,
    PROM_ASIS_REP FLOAT NULL,
    PROM_ASIS FLOAT NULL,

    COD_DEPE INT NOT NULL,
    RURAL_RBD BIT NOT NULL,
    ESTADO_ESTAB INT NULL,
    COD_ENSE INT NOT NULL

);


CREATE TABLE Keys  (
    RBD INT NOT NULL,
    NOM_RBD VARCHAR(255) NOT NULL

);

CREATE TABLE REGION (
    RBD INT NOT NULL,
    COD_REG_RBD INT NOT NULL,
    COD_PRO_RBD INT NULL,
    COD_COM_RBD INT NOT NULL,
    COD_DEPROV_RBD INT NULL
);
